version: 2
sources:
  - name: public
    tables:
      - name: inventory
        description: "Stores inventory information for each film at each store."
        columns:
          - name: inventory_id
            description: "Primary key for inventory."
            tests:
              - unique
              - not_null
          - name: film_id
            description: "Foreign key to film."
            tests:
              - not_null
              - relationships:
                  to: source('public', 'film')
                  field: film_id
          - name: store_id
            description: "Foreign key to store."
            tests:
              - not_null
              - relationships:
                  to: source('public', 'store')
                  field: store_id
          - name: last_update
            description: "Timestamp of last update."
            tests:
              - not_null

      - name: staff
        description: "Stores staff information."
        columns:
          - name: staff_id
            description: "Primary key for staff."
            tests:
              - unique
              - not_null
          - name: first_name
            description: "Staff member's first name."
            tests:
              - not_null
          - name: last_name
            description: "Staff member's last name."
            tests:
              - not_null
          - name: address_id
            description: "Foreign key to address."
            tests:
              - not_null
              - relationships:
                  to: source('public', 'address')
                  field: address_id
          - name: email
            description: "Staff member's email address."
          - name: store_id
            description: "Foreign key to store."
            tests:
              - not_null
              - relationships:
                  to: source('public', 'store')
                  field: store_id
          - name: active
            description: "Indicates if the staff member is active."
            tests:
              - not_null
          - name: username
            description: "Staff member's username."
            tests:
              - not_null
          - name: password
            description: "Staff member's password (nullable)."
          - name: last_update
            description: "Timestamp of last update."
            tests:
              - not_null
          - name: picture
            description: "Staff member's picture (nullable)."

      - name: store
        description: "Stores store information."
        columns:
          - name: store_id
            description: "Primary key for store."
            tests:
              - unique
              - not_null
          - name: manager_staff_id
            description: "Foreign key to staff (manager)."
            tests:
              - not_null
              - relationships:
                  to: source('public', 'staff')
                  field: staff_id
          - name: address_id
            description: "Foreign key to address."
            tests:
              - not_null
              - relationships:
                  to: source('public', 'address')
                  field: address_id
          - name: last_update
            description: "Timestamp of last update."
            tests:
              - not_null